### ISSUE TITLE
64 bit Shader Example crashes with AV.

### ISSUE THREAD

**Issue by DJMaster** [CWBudde/PasSFML#1]
![passfml shader example 64 bit](https://cloud.githubusercontent.com/assets/12114234/8398073/7cc557d4-1de2-11e5-83ae-a209c6539417.png)

64 bit PasSFML Shader Example crashes with AV (compiled to x86_64 target with FPC/Lazarus svn trunk).

32 bit PasSFML Shader Example works properly.

**Comment by refi64** [comment]
@DJMaster Could you try applying this patch:

``` diff
diff --git a/Source/SfmlGraphics.pas b/Source/SfmlGraphics.pas
index 77abcab..a2b6fc6 100644
--- a/Source/SfmlGraphics.pas
+++ b/Source/SfmlGraphics.pas
@@ -165,6 +165,9 @@ type
   TSfmlRenderStates = record
     BlendMode: TSfmlBlendMode;
     Transform: TSfmlTransform;
+    {$ifdef CPU64}
+    dummy: Single; { Padding }
+    {$endif}
     Texture: PSfmlTexture;
     Shader: PSfmlShader;
   end;
```

**Comment by DJMaster** [comment]
Thank you kirbyfan64, I confirm that your patch spotted the issue.

**Comment by refi64** [comment]
@DJMaster @CWBudde  Yeah, this is _really_ weird. It seems like the C compiler is padding CSFML's structs with extra bytes to make up for 8-byte pointers on x64, but FPC doesn't for some weird reason.

**Comment by CWBudde** [comment]
Should be solved now
