### ISSUE TITLE
MouseMoved event is not working properly.

### ISSUE THREAD

**Issue by ghost** [CWBudde/PasSFML#6]
The MouseMoved event is not working properly (http://www.sfml-dev.org/tutorials/2.3/window-events.php#the-mousemoved-event).

Event is only fired when pressing a mouse button. Mouse X value maps to Event.MouseMove.Y. Event.MouseMove.X is always zero.

OS: GNU/Linux 4.1.4-1 (Arch Linux x86_64; SFML 2.3.1; CSFML 2.3)

``` pascal
program MouseMove;

uses
  SfmlSystem in '../PasSFML/Source/SfmlSystem.pas',
  SfmlWindow in '../PasSFML/Source/SfmlWindow.pas';

var
  Window: TSfmlWindow;
  Event: TSfmlEvent;

begin
  Window := TSfmlWindow.Create(SfmlVideoMode(800, 600), 'MouseMove', [sfClose]);

  while Window.IsOpen do
  begin
    while Window.PollEvent(Event) do
    begin
      if Event.EventType = sfEvtMouseMoved then
      begin
        WriteLn('X: ', Event.MouseMove.X);
        WriteLn('Y: ', Event.MouseMove.Y);
      end;
    end;
  end;
end.
```

**Comment by CWBudde** [comment]
Just fixed this issue. It was due to a new event, which had been introduced in v2.3, but not mentioned in prominently.
