### ISSUE TITLE
SfmlNetwork.pas issues

### ISSUE THREAD

**Issue by TwistedBit** [CWBudde/PasSFML#7]
Issue 1:
I think that TSfmlSocketStatus should be:

``` pascal
TSfmlSocketStatus = (sfSocketDone, sfSocketNotReady, sfSocketPartial,
    sfSocketDisconnected, sfSocketError);
```

instead of

``` pascal
TSfmlSocketStatus = (sfSocketDone, sfSocketNotReady, sfSocketDisconnected,
    sfSocketError);
```

Issue 2:
For all port values a byte is used. Ports can have numbers between 0..65535 and the equivalent of an unsigned short in C and C++ for Delphi and Lazarus/Fpc is a word.

Is this correct or I am wrong ?
I am using V2.3 binaries with Lazarus 1.4.4

**Comment by CWBudde** [comment]
Fixed this now.
