### ISSUE TITLE
sfml libraries on ubuntu

### ISSUE THREAD

**Issue by ghost** [CWBudde/PasSFML#8]
Hello I am trying lazarus and sfml  on ubuntu 16 I already installed  sfml package but  it does no work
The error is:
/usr/bin/ld: can not found -lcsfml-window
/usr/bin/ld: can not found  -lcsfml-system

I need you help.
regards.....

**Comment by refi64** [comment]
You need to also install `libcsfml-dev`.

**Comment by ghost** [comment]
@ kirbyfan64  Thanks for you help
regards......

**Comment by CWBudde** [comment]
I just added a comment about this in the readme file.
