### ISSUE TITLE
SfmlNetwork missing functions

### ISSUE THREAD

**Issue by TwistedBit** [CWBudde/PasSFML#9]
Hello,
Some functions are missing from file SfmlNetwork.pas:
- sfTcpSocket_sendPartial - TcpSocket.h;
- sfSocketSelector_addTcpSocket - SocketSelector.h
- sfSocketSelector_addUdpSocket - SocketSelector.h
- sfSocketSelector_removeTcpSocket - SocketSelector.h
- sfSocketSelector_removeUdpSocket - SocketSelector.h

I have them implemented in my copy, but I don't know how to pass them to you.
Any advice ?

**Comment by refi64** [comment]
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/using-pull-requests/

**Comment by CWBudde** [comment]
Just implemented the missing features.
